#!/bin/bash
# anti-api
# Auto-generated by ProTab

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/terminal_helper.sh"

run_in_terminal "bash \"/Users/inkling/Desktop/anti-api/start.command\""
osascript -e 'display notification "anti-api" with title "ProTab"'
