#!/bin/bash
# tothemoonproj
# Auto-generated by ProTab

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/terminal_helper.sh"

run_in_terminal "bash \"/Users/inkling/Desktop/tothemoon/a.command\""
osascript -e 'display notification "tothemoonproj" with title "ProTab"'
